### ISSUE TITLE
Cannot place TORCH

### ISSUE THREAD

**Issue by SlimeDog** [XZot1K/PhysicsToGo#10]
Spigot 1.15.2
PTG 2.0.3

With the default configuration
```
place-removal: true
place-removal-delay: 20
place-only-effected:
  - "TORCH"
```
one cannot place a torch (or redstone_torch). With slightly modified configuration
```
place-removal: true
place-removal-delay: 20
place-only-effected: []
```
one cannot place any block. Why would I want **place-removal:true** by default? Am I missing something?

**Comment by XZot1K** [comment]
> 
> 
> Spigot 1.15.2
> PTG 2.0.3
> 
> With the default configuration
> 
> ```
> place-removal: true
> place-removal-delay: 20
> place-only-effected:
>   - "TORCH"
> ```
> 
> one cannot place a torch (or redstone_torch). With slightly modified configuration
> 
> ```
> place-removal: true
> place-removal-delay: 20
> place-only-effected: []
> ```
> 
> one cannot place any block. Why would I want **place-removal:true** by default? Am I missing something?

One line 99 and through the rest of the method (https://github.com/XZot1K/PhysicsToGo/blob/master/src/xzot1k/plugins/ptg/core/Listeners.java), you can see exactly what is going on! So basically, the whitelist will only provide PTG regeneration/removal effects on those particular materials. Since REDSTONE_TORCH contains the word TORCH, that is why that material is also blocked. Set the "place-removal" to false to disable that removal over time effects completely, but increasing the delay will of course allow the material to stay longer! Keep in mind the any other plugins that cancel the event and/or are hooked into will stop the plugin from modifying that instance.

**Comment by SlimeDog** [comment]
> place-removal: false

That is exactly what I have done. I am still having trouble thinking of a use case where it should be true. Just my lack of imagination.

**Comment by XZot1K** [comment]
> 
> 
> > place-removal: false
> 
> That is exactly what I have done. I am still having trouble thinking of a use case where it should be true. Just my lack of imagination.

It's mainly there for those who are doing things like open world pvp. It's a tool that is there for even the most specific needs!

**Comment by SlimeDog** [comment]
Thanks.
