### ISSUE TITLE
Newer version ?

### ISSUE THREAD

**Issue by SlimeDog** [XZot1K/PhysicsToGo#4]
Spigot 1.14-pre5 latest (2167)
PTG 1.8.4

On server start-up:
```
[23:50:02] [Server thread/INFO]: [PhysicsToGo] Enabling PhysicsToGo v1.8.4
[23:50:02] [Server thread/INFO]: PTG - Setting up required requisites...
[23:50:02] [Server thread/INFO]: PTG - There seems to be a new version on the PhysicsToGo page.
[23:50:02] [Server thread/INFO]: PTG - Version 1.8.4 has been successfully enabled!
```
The latest version on PTG Spigot page is 1.8.4

**Comment by XZot1K** [comment]
Not quite sure what the issue is here. Please elaborate.

**Comment by SlimeDog** [comment]
There was no newer version, so far as I can determine.

Same issue occurs with PTG 1.8.4-B.

**Comment by XZot1K** [comment]
> There was no newer version, so far as I can determine.
> 
> Same issue occurs with PTG 1.8.4-B.

Are you referencing the Update Checker?

**Comment by SlimeDog** [comment]
I block update checking. Perhaps that is interpreted (incorrectly) as "new version"?

**Comment by XZot1K** [comment]
> I block update checking. Perhaps that is interpreted (incorrectly) as "new version"?

Update checker currently is unable to be disabled. It is automatic now since I removed the in-game notifications. But It only says "new version" when it finds an update period.  I will take a look to make sure it is returning correctly, but if it finds the latest version that does not match the current it finds in the plugin it will say "new version".

**Comment by SlimeDog** [comment]
Please make it a feature request: to block update checking in the plugin. I block it at the system level, and can verify that it is blocked. The available latest version is the version I am running.
