### ISSUE TITLE
connecting blocks connection broken after regeneration

### ISSUE THREAD

**Issue by xemnes** [XZot1K/PhysicsToGo#8]
having an issue where blocks like fences, walls, glass panes, stairs etc do not connect properly during regeneration, im going to assume this is because block physics is completely disabled during regeneration (though doesnt always seem to work).
i tried to blacklist these blocks, but it still blows up blocks that have connected to other blocks
heres a video: https://gfycat.com/CoolSleepyBrontosaurus
note that the pole is intact, but the fences connected to them arent, then upon regeneration, none of them are connected.
perhaps a feature to allow block physics on certain blocks like fences.

on that topic though, seems when water or lava enters blocks that were recently destroyed and it tries to regenerate where lava or water is now occupying that block, sometimes it doesnt overwrite when it should.
video: https://gfycat.com/CommonLimpFossa

finally, the option "help-needed-material" in the config, doesnt work for stuff on walls or ceilings like torches, signs and lanterns. options for what direction the block is connected to would be useful.

**Comment by XZot1K** [comment]
I apologize, I didn't see this issue get opened. The video you showed is an issue that has been on and off throughout versions of mc. Mainly because PTG uses block states and forces updates to ignore physics. It's something I'm attempting to address. As for the water, this is due to some issues in the past in terms of exploits, this is also something I'm working on. Lastly, the final issue is because that list is for blocks that need a block under it. I will look into those materials, but that was intended for doors and other double block materials like grass.

**Comment by GeorgeMixas** [comment]
I saw that this issue is closed but it's still present on 1.15.2 Should this be fixed? because I'm having the exact same problems.
